# Generated by Django 5.1.15 on 2026-04-13 07:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBrief',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('raw_idea', models.TextField(help_text='Idea cruda tal como la escribe el usuario o viene del spreadsheet')),
                ('enriched_brief', models.JSONField(blank=True, help_text='Brief expandido por BriefEnricherAgent (JSON estructurado)', null=True)),
                ('content_type', models.CharField(choices=[('post', 'Post (imagen)'), ('carousel', 'Carrusel'), ('reel', 'Reel (video)'), ('story', 'Story')], default='post', max_length=20)),
                ('aspect_ratio', models.CharField(default='4:5', max_length=10)),
                ('num_slides', models.PositiveSmallIntegerField(default=1, help_text='1 para post/reel/story, 2-10 para carrusel')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('enriching', 'Enriqueciendo brief'), ('ready', 'Listo para generar'), ('generating', 'Generando contenido'), ('review', 'En revisión'), ('approved', 'Aprobado'), ('scheduled', 'Programado'), ('published', 'Publicado'), ('failed', 'Fallido'), ('archived', 'Archivado')], default='draft', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('priority', models.PositiveSmallIntegerField(default=5, help_text='1=Urgente, 10=Baja')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefs', to='brands.brand')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_selected', models.BooleanField(default=False, help_text='Variante seleccionada para publicar')),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('alt_text', models.CharField(blank=True, max_length=1000)),
                ('generation_params', models.JSONField(blank=True, default=dict, help_text='Parámetros usados: model, temperature, prompts, seeds...')),
                ('generation_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='content.contentbrief')),
            ],
            options={
                'ordering': ['brief', 'version'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_type', models.CharField(choices=[('brief_enricher', 'Brief Enricher'), ('copy', 'Copy Agent'), ('image', 'Image Agent'), ('carousel', 'Carousel Agent'), ('video', 'Video Agent'), ('hashtag', 'Hashtag Agent')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('success', 'Exitoso'), ('failed', 'Fallido'), ('retrying', 'Reintentando')], default='pending', max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('provider', models.CharField(blank=True, help_text='openai, fal, creatomate...', max_length=50)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('attempt', models.PositiveSmallIntegerField(default=1)),
                ('max_attempts', models.PositiveSmallIntegerField(default=3)),
                ('brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='content.contentbrief')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='content.contentvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contentbrief',
            index=models.Index(fields=['brand', 'status'], name='content_con_brand_i_c90046_idx'),
        ),
        migrations.AddIndex(
            model_name='contentbrief',
            index=models.Index(fields=['scheduled_for'], name='content_con_schedul_07e493_idx'),
        ),
        migrations.AddIndex(
            model_name='contentbrief',
            index=models.Index(fields=['content_type'], name='content_con_content_3f335e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contentvariant',
            unique_together={('brief', 'version')},
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['brief', 'agent_type'], name='content_age_brief_i_1b573c_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status'], name='content_age_status_17ac9d_idx'),
        ),
    ]
