# Generated by Django 5.1.15 on 2026-04-13 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('founder_name', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('target_audience', models.TextField(blank=True, help_text='Descripción del cliente ideal')),
                ('brand_voice_prompt', models.TextField(blank=True, help_text='System prompt base inyectado en todas las generaciones de IA para esta marca')),
                ('tone_adjectives', models.JSONField(blank=True, default=list, help_text='Lista de adjetivos de tono: cercano, educativo, directo...')),
                ('tone_description', models.TextField(blank=True, help_text='Descripción libre del tono')),
                ('forbidden_words', models.JSONField(blank=True, default=list)),
                ('color_primary', models.CharField(blank=True, help_text='HEX #RRGGBB', max_length=7)),
                ('color_secondary', models.CharField(blank=True, max_length=7)),
                ('color_background', models.CharField(blank=True, max_length=7)),
                ('color_accent', models.CharField(blank=True, max_length=7)),
                ('color_text', models.CharField(blank=True, max_length=7)),
                ('default_hashtags', models.JSONField(blank=True, default=list)),
                ('default_language', models.CharField(default='es', max_length=10)),
                ('preferred_image_style', models.CharField(blank=True, max_length=200)),
                ('preferred_aspect_ratios', models.JSONField(blank=True, default=list, help_text='Ej: ["4:5", "1:1", "9:16"]')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InstagramAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ig_user_id', models.CharField(help_text='Instagram User ID de la Graph API', max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('access_token', models.TextField(help_text='Token cifrado en producción')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('page_id', models.CharField(blank=True, help_text='Facebook Page ID vinculado', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to='brands.brand')),
            ],
            options={
                'unique_together': {('brand', 'ig_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='editor', max_length=10)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='brands.brand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'brand')},
            },
        ),
    ]
