# Generated by Django 5.1.15 on 2026-04-13 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('image', 'Imagen'), ('video', 'Video'), ('thumbnail', 'Thumbnail'), ('audio', 'Audio')], max_length=20)),
                ('source', models.CharField(choices=[('generated', 'Generado por IA'), ('uploaded', 'Subido manualmente'), ('template', 'Renderizado de template')], default='generated', max_length=20)),
                ('file_url', models.URLField(help_text='URL en S3/R2')),
                ('file_key', models.CharField(help_text='Key en el bucket', max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('mime_type', models.CharField(default='image/jpeg', max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, help_text='Solo para video/audio', null=True)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Orden dentro del carrusel (0-indexed)')),
                ('generation_prompt', models.TextField(blank=True)),
                ('generation_params', models.JSONField(blank=True, default=dict)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='content.contentvariant')),
            ],
            options={
                'ordering': ['variant', 'position'],
            },
        ),
    ]
