# Generated by Django 5.1.15 on 2026-04-13 07:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brands', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishingSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_for', models.DateTimeField()),
                ('status', models.CharField(choices=[('queued', 'En cola'), ('publishing', 'Publicando'), ('published', 'Publicado'), ('failed', 'Fallido'), ('cancelled', 'Cancelado')], default='queued', max_length=20)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='brands.instagramaccount')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='content.contentvariant')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('container_id', models.CharField(blank=True, max_length=100)),
                ('media_id', models.CharField(blank=True, max_length=100)),
                ('permalink', models.URLField(blank=True)),
                ('api_response', models.JSONField(blank=True, default=dict)),
                ('error_detail', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='brands.instagramaccount')),
                ('schedule', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publication', to='publishing.publishingschedule')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddIndex(
            model_name='publishingschedule',
            index=models.Index(fields=['status', 'scheduled_for'], name='publishing__status_964b6a_idx'),
        ),
    ]
